on:
  push:
    branches:
      - main

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          #port: ${{ secrets.FTP_PORT }} # Make sure this is just the port number
          remote_path: 'C:\Users\zamplia\Desktop\sachintest'
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}

